//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string DASH = "dash";
        
        public const string SECOND = "second";
        
        public const string FIRST = "first";
        
        public const string THIRD = "third";
        
        public const string LEFT = "left";
        
        public const string RIGHT = "right";
        
        public const string ALL = "all";
        
        public const string FIRE = "fire";
        
        public const string POSADKA = "posadka";
    }
}
